#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex selfreview.tex && latex selfreview.tex &&  latex selfreview.tex && bibtex selfreview && latex selfreview.tex && latex selfreview.tex && latex selfreview.tex && echo "-----------------------------" && dvips selfreview.dvi -o && ps2pdf selfreview.ps && echo " "
